version: '3.3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_net

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wordpress_net:
    driver: bridge

