version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: no
    env_file: .env 
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - wordpress-network

  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    env_file: .env
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - wordpress-network

volumes:
    db_data: {}
    wordpress_data: {}

networks:
  wordpress-network:
    driver: bridge

